// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.Data;

namespace server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200804022132_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("server.Models.User.User", b =>
                {
                    b.Property<string>("Tag")
                        .HasColumnType("character varying(15)")
                        .HasMaxLength(15);

                    b.Property<List<string>>("Activity")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Notifications")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("SessionKey")
                        .HasColumnType("text");

                    b.Property<List<string>>("Tickets")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Tag");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
